security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Entity\Utilisateur: bcrypt

    role_hierarchy:
        ROLE_PROF:        ROLE_USER
        ROLE_ADMIN:       ROLE_PROF
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_PROF]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin_homepage
            logout:
                target: /login
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_PROF,ROLE_PARENT] }
        - { path: ^/confirmed, role: ROLE_ADMIN }