<?php

namespace UserBundle\Repository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveRepository extends \Doctrine\ORM\EntityRepository
{
    public function eleve()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('count(e.id)');
        return $qb->getQuery()->getSingleScalarResult();
    }
}
