<?php

namespace UserBundle\Repository;

/**
 * ParentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentsRepository extends \Doctrine\ORM\EntityRepository
{
}
