<?php

namespace BackBundle\Repository;

/**
 * CommuniquerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuniquerRepository extends \Doctrine\ORM\EntityRepository
{
}
