<?php

namespace BackBundle\Repository;

/**
 * TypeFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
